/* Generated By:JavaCC: Do not edit this line. SelectConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SelectConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SELECT = 4;
  /** RegularExpression Id. */
  int FROM = 5;
  /** RegularExpression Id. */
  int WHERE = 6;
  /** RegularExpression Id. */
  int EXIT = 7;
  /** RegularExpression Id. */
  int STAR = 8;
  /** RegularExpression Id. */
  int EQUAL = 9;
  /** RegularExpression Id. */
  int QUOTATION = 10;
  /** RegularExpression Id. */
  int SPACE = 11;
  /** RegularExpression Id. */
  int NUMBER = 12;
  /** RegularExpression Id. */
  int SEMICOLON = 13;
  /** RegularExpression Id. */
  int CAPITAL = 14;
  /** RegularExpression Id. */
  int ALPHANUMERIC = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<SELECT>",
    "<FROM>",
    "<WHERE>",
    "<EXIT>",
    "\"*\"",
    "\"=\"",
    "\"\\\"\"",
    "\" \"",
    "<NUMBER>",
    "\";\"",
    "<CAPITAL>",
    "<ALPHANUMERIC>",
  };

}
