/* Generated By:JavaCC: Do not edit this line. SqlConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SqlConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CREATE = 4;
  /** RegularExpression Id. */
  int DATABASE = 5;
  /** RegularExpression Id. */
  int SELECT = 6;
  /** RegularExpression Id. */
  int FROM = 7;
  /** RegularExpression Id. */
  int WHERE = 8;
  /** RegularExpression Id. */
  int EXIT = 9;
  /** RegularExpression Id. */
  int STAR = 10;
  /** RegularExpression Id. */
  int EQUAL = 11;
  /** RegularExpression Id. */
  int QUOTATION = 12;
  /** RegularExpression Id. */
  int SPACE = 13;
  /** RegularExpression Id. */
  int NUMBER = 14;
  /** RegularExpression Id. */
  int SEMICOLON = 15;
  /** RegularExpression Id. */
  int ALPHANUMERIC = 16;
  /** RegularExpression Id. */
  int LISTATTR = 17;
  /** RegularExpression Id. */
  int COMMA = 18;
  /** RegularExpression Id. */
  int CAPITAL = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<CREATE>",
    "<DATABASE>",
    "<SELECT>",
    "<FROM>",
    "<WHERE>",
    "<EXIT>",
    "\"*\"",
    "\"=\"",
    "\"\\\"\"",
    "\" \"",
    "<NUMBER>",
    "\";\"",
    "<ALPHANUMERIC>",
    "<LISTATTR>",
    "\",\"",
    "<CAPITAL>",
  };

}
